experiment:
  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/splitting/0/0/train.tsv
    validation_path: ../data/{0}/splitting/0/0/val.tsv
    test_path: ../data/{0}/splitting/0/test.tsv
  dataset: yelp2018

  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:

    Random:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
      seed: 42

    MostPop:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20

    ItemKNN:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      neighbors: [uniform, 5, 1000]
      asymmetric_alpha: [uniform, 0, 2]
      tversky_alpha: [uniform, 0, 2]
      tversky_beta: [uniform, 0, 2]
      similarity: [cosine, jaccard, dot, asym, tversky]

    EASER:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      l2_norm: [uniform, 10, 10e5]
      neighborhood: -1

    RP3beta:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      neighborhood: [uniform, 50, 10000]
      alpha: [uniform, 0, 5]
      beta: [uniform, 0, 5]
      normalize_similarity: [True, False]

    external.SVDGCN:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      factors: 64
      epochs: 15
      batch_size: 128
      l_w: 0.01
      lr: [uniform, 7, 9]
      req_vec: [quniform, 60, 90, 1]
      beta: 2.0
      alpha: [uniform, 2, 3]
      coef_u: [loguniform, -2.30258509299, -0.105360516]  # 0.1 - 0.9
      coef_i: [loguniform, -2.30258509299, -0.105360516]  # 0.1 - 0.9
      seed: 123

    external.FPSR:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      eigen_dim: [64,128,256]
      batch_size: 64  # only for evaluation
      l_w: [0.1, 0.2, 0.3, 0.4, 0.5]
      rho: 500
      w_1: [0.1, 0.2, 0.5, 0.8, 1, 2, 5]
      w_2: [0.1, 0.2, 0.5, 0.8, 1, 2, 5]
      eta: [0.01, 0.1, 1]
      eps: 5e-3
      tau: [0.1, 0.2, 0.3, 0.4, 0.5]
      seed: 2026

    external.PSGE:
      meta:
        save_recs: False
        verbose: True
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      factors: [quniform, 10, 2000, 1]
      alpha: [uniform, 0, 1]
      beta: [uniform, 0, 1]
      seed: 42

    PureSVD:
      meta:
        save_recs: False
        verbose: True
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      factors: [quniform, 10, 2000, 1]
      seed: 42

    external.SVDGCNS:
      meta:
        save_recs: False
        verbose: False
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      req_vec: [quniform, 15, 90, 1]
      beta: [uniform, 2.0, 6.0]
      alpha: [uniform, 2.0, 6.0]
      seed: 42

    external.SVD_AE:
      meta:
        save_recs: False
        verbose: True
        validation_metric: Recall@20
        hyper_max_evals: 20
        hyper_opt_alg: tpe
      factors: [quniform, 10, 2000, 1]
      seed: 42