experiment:

  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_gde.tsv
    test_path: ../data/{0}/test_gde.tsv

  dataset: pinterest
  top_k: 20
  evaluation:
    cutoffs: [10,20]
    simple_metrics: [nDCG, Recall]

  gpu: -1
  external_models_path: ../external/models/__init__.py

  models:
    external.GDE:
      meta:
        save_recs: False
        verbose: False
      batch_size: 256
      factors: 64
      l_w: 0.01
      feature_type: smoothed
      smooth_ratio: 0.2
      rough_ratio: 0.0
      epochs: 400
      lr: 0.12
      dropout: 0.2
      beta: 5.0
      loss_type: adaptive
      seed: 42