experiment:

  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_svdgcn.tsv
    test_path: ../data/{0}/test_svdgcn.tsv

  dataset: yelp2015
  top_k: 20
  evaluation:
    cutoffs: [10,20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:
    external.GDE:
      meta:
        save_recs: False
        verbose: False
      batch_size: 256
      factors: 64
      l_w: 0.01
      feature_type: smoothed
      smooth_ratio: 0.3
      rough_ratio: 0.0
      epochs: 300
      lr: 0.01
      dropout: 0.1
      beta: 5.0
      loss_type: adaptive
      seed: 42