experiment:

  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_gde.tsv
    test_path: ../data/{0}/test_gde.tsv

  dataset: yelp2015
  top_k: 20
  evaluation:
    cutoffs: [10,20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:
    external.RSGDE:
      meta:
        save_recs: False
        verbose: True
      batch_size: 256
      factors: 64
      l_w: 0.01
      epochs: 30
      alpha: 3
      req_vec: 60
      beta: 2.0
      std: 0.02
      lr: 7.0
      coef_u: 0.7
      coef_i: 0.7
      seed: 42