experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_fpsr.tsv
    test_path: ../data/{0}/test_fpsr.tsv
    validation_path: ../data/{0}/valid_fpsr.tsv
  dataset: ml-20m
  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSRplus:
      meta:
        save_recs: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.3
      rho: 500
      w_1: 1.0
      w_2: 0.1
      eta: 1.0
      eps: 5e-3
      tau: 0.5
      pop_ratio: 0.1
      seed: 2026
    external.FPSRplusF:
      meta:
        save_recs: False
      eigen_dim: 256
      batch_size: 64
      l_w: 0.3
      rho: 500
      w_1: 1.0
      w_2: 0.1
      eta: 1.0
      eps: 5e-3
      tau: 0.5
      pop_ratio: 0.1
      seed: 2026